name: k8s-Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  TERRAFORM_VERSION: '1.5.7'

jobs:

  infra:
    runs-on: ubuntu-latest
    outputs:
      kubernetes_cluster_name: ${{ steps.apply.outputs.kubernetes_cluster_name }}
      primary_region: ${{ steps.apply.outputs.primary_region }}
      console_role: ${{ steps.apply.outputs.console_role }}
      admin_group: ${{ steps.apply.outputs.admin_group }}
      alb_controller_role: ${{ steps.apply.outputs.alb_controller_role }}
      workload_identity_role: ${{ steps.apply.outputs.workload_identity_role }}

    environment:
      name: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v3

    - id: setup
      name: Setup `terraform`
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - id: apply
      name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BACKEND_BUCKET_NAME: ${{ vars.BACKEND_BUCKET_NAME }}
        BACKEND_REGION: ${{ vars.BACKEND_REGION }}
        BACKEND_KEY: ${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT_NAME }}
      working-directory: ${{ vars.TERRAFORM_WORKING_DIRECTORY }}
      run: |
        terraform init \
          -backend-config='bucket='$BACKEND_BUCKET_NAME \
          -backend-config='region='$BACKEND_REGION \
          -backend-config="key=${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT_NAME }}"

        terraform apply -target "random_shuffle.az" -auto-approve
        terraform apply -auto-approve

        kubernetes_cluster_name=$(terraform output -raw kubernetes_cluster_name)
        echo "kubernetes_cluster_name=$kubernetes_cluster_name" >> "$GITHUB_OUTPUT"

        primary_region=$(terraform output -raw primary_region)
        echo "primary_region=$primary_region" >> "$GITHUB_OUTPUT"

        console_role=$(terraform output -raw console_role_arn)
        echo "console_role=$console_role" >> "$GITHUB_OUTPUT"

        alb_controller_role=$(terraform output -raw alb_controller_role)
        echo "alb_controller_role=$alb_controller_role" >> "$GITHUB_OUTPUT"

        workload_identity_role=$(terraform output -raw workload_identity_role)
        echo "workload_identity_role=$workload_identity_role" >> "$GITHUB_OUTPUT"

        admin_group=$(terraform output -raw admin_group_arn)
        echo "admin_group=$admin_group" >> "$GITHUB_OUTPUT"
        
  k8s:
    runs-on: ubuntu-latest
    needs: infra

    environment:
      name: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v3

    - id: setup
      name: Setup `terraform`
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - id: Apply
      name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BACKEND_BUCKET_NAME: ${{ vars.BACKEND_BUCKET_NAME }}
        BACKEND_REGION: ${{ vars.BACKEND_REGION }}
        BACKEND_KEY: ${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT_NAME }}
        TF_VAR_application_name: ${{ vars.APPLICATION_NAME }}
        TF_VAR_environment_name: ${{ vars.ENVIRONMENT_NAME }}
        TF_VAR_cluster_name: ${{ needs.infra.outputs.kubernetes_cluster_name }}
        TF_VAR_primary_region: ${{ needs.infra.outputs.primary_region }}
        TF_VAR_alb_controller_role: ${{ needs.infra.outputs.alb_controller_role }}
        TF_VAR_workload_identity_role: ${{ needs.infra.outputs.workload_identity_role }}
      working-directory: ./src/terraform/k8s
      run: |
        terraform init \
          -backend-config='bucket='$BACKEND_BUCKET_NAME \
          -backend-config='region='$BACKEND_REGION \
          -backend-config="key=${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT_NAME }}-k8s"
          
        terraform apply -auto-approve

    - name: Setup eksctl
      run: |
        # Set ARCH to the appropriate value if running on a different architecture
        ARCH=amd64
        PLATFORM=$(uname -s)_$ARCH

        # Download eksctl
        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"

        # Optionally verify checksum
        curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check

        # Extract and move to a location in PATH
        tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        rm eksctl_$PLATFORM.tar.gz

        # Verify installation
        eksctl version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ needs.infra.outputs.primary_region }}

    - name: Test eksctl command
      run: |
        eksctl get clusters
        eksctl get iamidentitymapping \
          --cluster ${{ needs.infra.outputs.kubernetes_cluster_name }} \
          --region=${{ needs.infra.outputs.primary_region }}

        eksctl create iamidentitymapping \
          --cluster ${{ needs.infra.outputs.kubernetes_cluster_name }} \
          --region=${{ needs.infra.outputs.primary_region }} \
          --arn ${{ needs.infra.outputs.console_role }} \
          --group eks-console-dashboard-full-access-group \
          --no-duplicate-arns

        eksctl create iamidentitymapping \
          --cluster ${{ needs.infra.outputs.kubernetes_cluster_name }} \
          --region=${{ needs.infra.outputs.primary_region }} \
          --arn arn:aws:iam::312344499806:user/markti \
          --group eks-console-dashboard-restricted-access-group \
          --no-duplicate-arns
